In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as ex

In [5]:
df =pd.read_csv("../data/raw/indian_startup_funding.csv")

In [6]:
df.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [7]:
df.shape

(1100, 8)

In [8]:
df.columns

Index(['Startup', 'Industry', 'SubVertical', 'City', 'Investors',
       'InvestmentType', 'InvestmentAmount_USD', 'Date'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   str
 1   Industry              1100 non-null   str
 2   SubVertical           1100 non-null   str
 3   City                  1100 non-null   str
 4   Investors             1100 non-null   str
 5   InvestmentType        1100 non-null   str
 6   InvestmentAmount_USD  1100 non-null   int64
 7   Date                  1100 non-null   str
dtypes: int64(1), str(7)
memory usage: 68.9 KB

In [10]:
df.isnull().sum()

Startup                 0
Industry                0
SubVertical             0
City                    0
Investors               0
InvestmentType          0
InvestmentAmount_USD    0
Date                    0
dtype: int64

In [11]:
df.describe()

       InvestmentAmount_USD
count          1.100000e+03
mean           2.553295e+07
std            7.266655e+07
min            5.000000e+03
25%            1.697500e+05
50%            1.114500e+06
75%            1.017250e+07
max            5.746760e+08

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df=df.drop_duplicates()

In [15]:
df.shape

(1100, 8)

In [16]:
df["Date"]=pd.to_datetime(df["Date"])

C:\Users\varun\AppData\Local\Temp\ipykernel_20052\1380596044.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date"]=pd.to_datetime(df["Date"])

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   str
 1   Industry              1100 non-null   str
 2   SubVertical           1100 non-null   str
 3   City                  1100 non-null   str
 4   Investors             1100 non-null   str
 5   InvestmentType        1100 non-null   str
 6   InvestmentAmount_USD  1100 non-null   int64
 7   Date                  1100 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 68.9 KB

In [18]:
df.to_csv("../data/cleaned/cleaned_startup_funding.csv", index=False)